### ISSUE TITLE
Folders: show contents button when chosen != folder

### ISSUE THREAD

**Issue by dvorapa** [dvorapa/stepslow#64]

**Comment by Roshani9731** [comment]
Hy, I want contribute in this issue can help me?

**Comment by dvorapa** [comment]
Hi, sure! Start by building the flutter project and running it in emulator/device and making yourself familiar with the code.

The issue in detail: when on the page with folders listing, if you select a folder with no children folders, you are automatically put on a songs listing. But when you choose a folder with some children folders, you are not. This is correct behavior, but it has got one caveat, when user wants to play a song from the folder with children folders. There should be a button for that case indicating, that you can play songs from this folder too leading to the songs listing. Button should be shown when chosenFolder != folder and also when songs in folder are > 0.

Note that the button should match the app design patterns (should be incorporated in CONTRIBUTING.md once I get some time to write it).

Feel free to ask any question or share any inconvenience with me so I can help to make it easier for you!

**Comment by dvorapa** [comment]
@Roshani9731 I'm sorry, but this issue is the last one to be solved before the first public release. As I aim to release it ASAP, I'm going to solve the issue by myself. You can inspire yourself by my solution and pick a different issue to work on
